### ISSUE TITLE
Found error while running the code.

### ISSUE THREAD

**Issue by rajansh87** [tushar5526/Covid_visualisation#1] opened 2020-08-18 16:16 UTC
I am working on a project that something looks like this one, but while testing this project in my system it showed this error:

Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\Covid_visualisation-master\main.py", line 26, in <module>
    if float(city_data[i]['deaths']) > 50:
KeyError: 'deaths'

Can you help and suggest what's the problem?
I think this is due to some kind of null value in the dataset.

**Comment by tushar5526** [comment] 2020-08-18 16:42
Hey thanks for checking it out.
I reproduced the bug as you mentioned.
I am fetching a JSON from an API and then parsing the data so it's probably due to API changes. 
Will fix it and update it. Thanks ;)


Update : Daman in not having any key 'deaths' so we are getting a not found key error, fixed it !

**Comment by tushar5526** [comment] 2020-08-18 16:59
@rajansh87
Also, this code was tested on ubuntu 18.04 so you might have to change the last line in main.py
```
os.system('google-chrome map.html') 
```
to something that works on windows.

**Comment by rajansh87** [comment] 2020-08-18 19:01
it says the error is in line 26. and I don't think that OS would affect this program. Please have a look and check it out and do inform me too because I want to use it as a reference for mine.

**Comment by tushar5526** [comment] 2020-08-19 15:46
@rajansh87 Works fine for me, did you pulled the recent changes ?
Can  you tell me the errors too ?

**Comment by rajansh87** [comment] 2020-08-19 17:39
@tushar5526 yeah, now it is working fine.

**Comment by tushar5526** [comment] 2020-08-19 17:52
Closing the issue @rajansh87

**Closed as completed by tushar5526** 2020-08-19 17:52 UTC
